# Generated by Django 5.0.4 on 2024-04-12 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0002_remove_author_collections_remove_author_stories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.ManyToManyField(blank=True, related_name='anthologies', to='authors.author')),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('collection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cover', serialize=False, to='anthologies.collection')),
                ('image', models.ImageField(upload_to='anthologies/covers/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('track', models.FileField(upload_to='anthologies/stories/%Y/%m/%d/')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='anthologies.collection')),
            ],
        ),
    ]
