# Generated by Django 5.0.4 on 2024-04-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='authors/img/%Y/%m/%d/')),
                ('types', models.TextField()),
                ('collections', models.IntegerField()),
                ('stories', models.IntegerField()),
                ('deceased', models.BooleanField()),
            ],
        ),
    ]
