# Generated by Django 5.0.4 on 2024-04-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='collections',
        ),
        migrations.RemoveField(
            model_name='author',
            name='stories',
        ),
    ]
